### ISSUE TITLE
Awards - Add support for Google Cloud Storage backend for image uploads

### ISSUE THREAD

**Issue by markyjones** [seatgeek/backstage-plugins#37]
Add support for Google Cloud Storage backend for image uploads using `@tweedegolf/sab-adapter-google-cloud`.

We have a Pull Request ready if you are happy with this contribution?

Configuration would look like:

```yaml
awards:
  storage:
    gcs:
      bucket: gs://backstage-awards # required
      keyFilename: path/to/keyFile.json # optional: defaults to GOOGLE_APPLICATION_CREDENTIALS
```
