### ISSUE TITLE
awards: add `awards.storage.type` key to specify which engine to use

### ISSUE THREAD

**Issue by zhammer** [seatgeek/backstage-plugins#39]
https://github.com/seatgeek/backstage-plugins/pull/34 did not properly fix the problem of multiple `awards.storage` engines being configured in an application with multiple configs (e.g. in `app-config.yaml` i have `awards.storage.fs: {...}` and in `app-config.prod.yaml` i have `awards.storage.s3: {...}`.

@freben gave [the suggestion](https://discord.com/channels/687207715902193673/687235481154617364/1212646390887481364) to add a `type` field, where in `app-config.prod.yaml` you would write:

```yaml
awards:
  storage:
    type: s3
    s3: {...}
```

---

**zhammer — 02/28/2024 2:49 PM**
is there a way to override (delete, nullify) a config dict in a config file overlay? e.g. 

```yml
# application-config.yaml
my-plugin:
  storage:
    filesystem:
      directory: tmp/
```

```yml
# application-config.production.yaml
my-plugin:
  storage:
    # we want this gone in production
    filesystem: null
    s3:
      bucket: my-bucket
```

this isn't working for us. trying to get this right for our own OSS plugin: https://github.com/seatgeek/backstage-plugins/commit/e568c37f81c9f87728007a63ad44246419e6d8b5

**freben — Yesterday at 1:23 AM**
No. But we'd generally put a `type: s3` etc in there so that the reading code knows which subkey to dive in to
The it doesn't matter that there's an extra filsystem key hanging around
